
apiVersion: apps/v1
kind: Deployment
metadata:
  name: backend-user
  labels:
    app: backend-user
spec:
  replicas: 2
  selector:
    matchLabels:
      app: backend-user
  template:
    metadata:
      labels:
        app: backend-user
    spec:
      containers:
      - name: backend-user
        image: mvongphachant/udagram-api-user:latest
        ports:
        - containerPort: 8080
        env:
        - name: POSTGRES_USERNAME
          valueFrom:
            secretKeyRef:
              name: udagram-db-secret
              key: username
        - name: POSTGRES_PASSWORD
          valueFrom:
            secretKeyRef:
              name: udagram-db-secret
              key: password
        - name: POSTGRES_HOST
          valueFrom:
            secretKeyRef:
              name: udagram-db-secret
              key: host
        - name: POSTGRES_DB
          valueFrom:
            secretKeyRef:
              name: udagram-db-secret
              key: database
        - name: AWS_BUCKET
          value: "mv-udagram-1755272174"
        - name: AWS_REGION
          value: "us-east-1"
        - name: AWS_ACCESS_KEY_ID
          value: ""
        - name: AWS_SECRET_ACCESS_KEY
          value: ""
        - name: JWT_SECRET
          valueFrom:
            secretKeyRef:
              name: udagram-app-secret
              key: jwt-secret
        - name: URL
          value: "http://localhost:8100"
        resources:
          requests:
            memory: "512Mi"
            cpu: "250m"
          limits:
            memory: "1Gi"
            cpu: "500m"
        livenessProbe:
          httpGet:
            path: /api/v0/users
            port: 8080
          initialDelaySeconds: 60
          periodSeconds: 30
        readinessProbe:
          httpGet:
            path: /api/v0/users
            port: 8080
          initialDelaySeconds: 45
          periodSeconds: 10