apiVersion: apps/v1
kind: Deployment
metadata:
  name: backend-feed
  labels:
    app: backend-feed
spec:
  replicas: 2
  selector:
    matchLabels:
      app: backend-feed
  template:
    metadata:
      labels:
        app: backend-feed
    spec:
      containers:
      - name: backend-feed
        image: mvongphachant/udagram-api-feed:latest
        ports:
        - containerPort: 8080
        env:
        - name: POSTGRES_USERNAME
          value: "postgres"
        - name: POSTGRES_PASSWORD
          value: "test1111"
        - name: POSTGRES_HOST
          value: "db-demo.cjzyxofcgozz.us-east-1.rds.amazonaws.com"
        - name: POSTGRES_DB
          value: "demo1"
        - name: AWS_BUCKET
          value: "mv-785998958699"
        - name: AWS_REGION
          value: "us-east-1"
        - name: AWS_PROFILE
          value: "default"
        - name: JWT_SECRET
          value: "testing"
        - name: URL
          value: "http://localhost:8100"
        resources:
          requests:
            memory: "512Mi"
            cpu: "250m"
          limits:
            memory: "1Gi"
            cpu: "500m"
        livenessProbe:
          httpGet:
            path: /api/v0/feed
            port: 8080
          initialDelaySeconds: 60
          periodSeconds: 30
        readinessProbe:
          httpGet:
            path: /api/v0/feed
            port: 8080
          initialDelaySeconds: 45
          periodSeconds: 10